[pytest]
# Enable live logging in the console
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s

# Optional: You can also let pytest handle a second log file automatically
log_file = logs/pytest_session.log
log_file_level = DEBUG

pythonpath = .