[pytest]

base_url = https://automationexercise.com/

python_files = test_*.py

addopts =
    -v
    --html=reports/report.html
    --self-contained-html
    --alluredir=allure-results

# --------------------------------------------------
# Live Console Logging
# --------------------------------------------------

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s

# --------------------------------------------------
# Session Log
# --------------------------------------------------

log_file = logs/pytest_session.log
log_file_level = DEBUG

markers =
    smoke: Smoke Tests
    run: Test execution order
    regression: Regression Tests
    api: API Tests
    ui: UI Tests
    hybrid: Hybrid API + UI Tests
    self_healing: Rule-based self-healing tests
    ai: AI self-healing tests